#!/usr/bin/perl
#
use DBI;

# script to pull the schedule information
# from the database

use FindBin;
use Sys::Hostname;
use Cwd;
use File::Basename;
use lib "FindBin::Bin";
require "common.sub.pl";
require "config.pl";

my $current_dir = cwd();
my $current_date_time = `date '+%Y%m%d_%H%M%S'`;
chop($current_date_time);

my $db_name = dbName();
my $user = dbUser();
my $password = dbPassword();
my $host = hostname;
my $host_name = (split(/\./, $host))[0];

my $output_fname = "$current_dir/output/$host_name.$db_name.schedules.$current_date_time.out";
open(OUTPUT, ">$output_fname") || die "cannot open $output_fname";

#my $script_fname = basename($0);
my $script_fname = $0;
$current_date_time = `date '+%Y/%m/%d %H:%M:%S'`;
chop($current_date_time);
print OUTPUT "File generated by: $script_fname\n";
print OUTPUT "Schedule information from $host:$db_name as of $current_date_time\n";

my $dbh = connectToDB($db_name, $user, $password, $host);

my @satellites;
push(@satellites, "G08");
push(@satellites, "G08/RSO");
push(@satellites, "G08/SRSO");
push(@satellites, "G10");
push(@satellites, "G10/RSO");
push(@satellites, "G10/SRSO");
push(@satellites, "G11");
push(@satellites, "G11/RSO");
push(@satellites, "G11/SRSO");
push(@satellites, "G12");
push(@satellites, "G12/RSO");
push(@satellites, "G12/SRSO");
push(@satellites, "G13");
push(@satellites, "G13/RSO");
push(@satellites, "G13/SRSO");
push(@satellites, "G14");
push(@satellites, "G14/RSO");
push(@satellites, "G14/SRSO");
push(@satellites, "G15");
push(@satellites, "G15/RSO");
push(@satellites, "G15/SRSO");

my ($cmd, $time, $name, $abvr, $duration);

foreach $sat (@satellites) {
   $sql = "select sch.id, sch.time, sec.name, sec.abrv, sec.duration from Schedule sch, Sector sec where sch.sector = sec.id and sch.satellite = '$sat' order by sch.time";
   my $schedule_ref = $dbh->selectall_hashref($sql, 'time');
   print OUTPUT "Satellite: $sat\n";
   print OUTPUT "$sql\n";
   my @schedules = keys(%$schedule_ref);
   print OUTPUT "there are $#schedules records for $sat\n";
   foreach $schedule_time(sort(keys %$schedule_ref)) {
      $time = $schedule_ref->{$schedule_time}->{time};
      $name = $schedule_ref->{$schedule_time}->{name};
      $abrv = $schedule_ref->{$schedule_time}->{abrv};
      $duration = $schedule_ref->{$schedule_time}->{duration};
      print OUTPUT "\t$time $name $abrv $duration\n";
   }
   print OUTPUT "\n\n";
}
close(OUTPUT);
