#!/usr/bin/perl -Tw

use strict; 

use CGI qw(:cgi);                       # Include CGI functions
use CGI::Carp qw(fatalsToBrowser);      # Send error messages to browser for
                                        # test purposes
# the getinfo url
my $url = "http://www.eol.ucar.edu/cgi-bin/mss_retrieval/getinfo.cgi?";

# the CGI object
my $query = new CGI;

# the maximum size of the request (in GB)
my $max_size = .10;

# the files
my @files = param("mss_files");

# split out the size and filename from the mss_files parameter
my (@size, @filename, $total_size);
my $i;
for ( $i=0; $i <= $#files; $i++) {
	($size[$i], $filename[$i]) = split(/;/, $files[$i]);
} # end for

print $query->header();
print $query->start_html();
print "<h1>this is a test</h1>";
print $query->end_html();
#***********************************
sub fetch_js
{
   my $js = '';

   $js .= "function testit() {\n";
   $js .= "   alert('this is a test');\n";
   $js .= "}\n";

   return $js;


}
